---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kaigara-org
  namespace: kaigara
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kaiweb
    spec:
      containers:
      - name: kaiweb
        image: kaigara/web:latest
        ports:
        - containerPort: 8080
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-www-redirect
  namespace: kaigara
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx-www-redirect
    spec:
      containers:
      - name: nginx-www-redirect
        image: cmeulien/nginx-www-redirect
        ports:
        - containerPort: 80
